"""Balls: midpoint-radius intervals that contain every value they stand for.

Every function is scalar, one declaration per name, and returns a ball that
contains the exact result for every point of its inputs. Operands may be balls
or exact numbers. A `context=` (`BallContext`) sets the result precision.
"""

from .value import Ball, BallOrder
from .context import BallContext
from .constants import pi_ball, euler_e_ball, ln2_ball, log2_10_ball, euler_gamma_ball, catalan_ball
from .significance import bits_to_digits, digits_to_bits, radius_for_relative_digits, propagation_bound
from .special import (
    gamma,
    gammaln,
    digamma,
    erf,
    erfc,
    erfi,
    expi,
    sici,
    shichi,
    fresnel,
    lambertw,
    ndtr,
    log_ndtr,
    beta,
    betaln,
    poch,
    erfinv,
    ndtri,
    zeta,
    polygamma,
    hyp1f1,
    gammainc,
    gammaincc,
    hyp2f1,
    betainc,
)
from .elementary import (
    exp,
    expm1,
    exp2,
    log,
    log1p,
    log2,
    log10,
    sin,
    cos,
    tan,
    sin_cos,
    atan,
    asin,
    acos,
    atan2,
    sinh,
    cosh,
    tanh,
    asinh,
    acosh,
    atanh,
    pow,
    rootn,
)
from .math import (
    add,
    subtract,
    multiply,
    divide,
    reciprocal,
    abs,
    maximum,
    minimum,
    clip,
    square,
    sqrt,
    pow_int,
    ldexp,
    fma,
    round_midpoint,
    trim,
    add_error,
    stable_hash,
)
from .sets import (
    compare,
    contains,
    contains_zero,
    contains_ball,
    overlaps,
    contains_integer,
    union,
    intersection,
    split,
    to_float_if_certain,
    canonical,
    floor_if_certain,
    ceil_if_certain,
    round_half_even_if_certain,
    simplest_rational_in,
)
