"""Build every documentation program into one executable, run it once and
compare each program's output with docs/examples.json.

A generated driver imports each example as a module and calls its `main`
between marker lines, so the library and its shared generic code compile once.
Each example still has its own `main` and runs alone with
`pixi run mojo run -I src docs/examples/<name>.mojo`. A crash fails the
running example; the driver then restarts after it with `--from N`.
"""
import argparse
import difflib
import json
import re
import runpy
import subprocess
import sys
import time
from pathlib import Path

from docs_contract import EXAMPLES, ROOT, data

RUNNER = runpy.run_path(str(ROOT / 'tests/run.py'))
MARK = '@@apn-example'
_EVENT = re.compile(rf'^{MARK} (begin|pass|fail|end) ?(\d*)', re.M)


def driver_source(paths):
    stems = [Path(p).stem for p in paths]
    lines = ['"""Generated by scripts/verify_docs_examples.py: every documentation example in one program."""',
             'from std.sys import argv']
    lines += [f'import {stem}' for stem in stems]
    lines += ['', '', 'def main() raises:', '    var arguments = argv()',
              '    var start = atol(arguments[2]) if len(arguments) == 3 and arguments[1] == "--from" else 0']
    for index, stem in enumerate(stems):
        lines += [f'    if start <= {index}:',
                  f'        print("{MARK} begin {index}", flush=True)',
                  '        try:',
                  f'            {stem}.main()',
                  f'            print("{MARK} pass {index}", flush=True)',
                  '        except error:',
                  f'            print("{MARK} fail {index}", error, flush=True)']
    lines.append(f'    print("{MARK} end", flush=True)')
    return '\n'.join(lines) + '\n'


def parse(stdout):
    """{index: (passed, output, error)} for the programs that finished, the
    index of one that began and did not finish, and whether the run ended."""
    results, current, start, ended = {}, None, 0, False
    events = list(_EVENT.finditer(stdout))
    for position, event in enumerate(events):
        kind, index = event[1], int(event[2]) if event[2] else None
        if kind == 'begin':
            current, start = index, event.end() + 1
        elif kind in ('pass', 'fail'):
            following = events[position + 1].start() if position + 1 < len(events) else len(stdout)
            error = stdout[event.end():following].strip() if kind == 'fail' else ''
            results[index] = (kind == 'pass', stdout[start:event.start()], error)
            current = None
        else:
            ended = True
    return results, current, ended


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--only', help='Run only programs whose path contains this text')
    parser.add_argument('--optimization', type=int, choices=(0, 3), default=0,
                        help='0 (default, fastest to build) or 3')
    parser.add_argument('--compile-timeout', type=int, default=1800, help='Seconds for the build (default: 1800)')
    parser.add_argument('--run-timeout', type=int, default=600, help='Seconds per run (default: 600)')
    parser.add_argument('--output', default='.cache/docs-examples', help='Directory for the driver, binary and logs')
    args = parser.parse_args()
    folder = ROOT / args.output
    folder.mkdir(parents=True, exist_ok=True)
    declared = data('examples.json')['examples']
    paths = [path for path in declared if not args.only or args.only in path]
    assert paths, 'No matching documentation programs'
    driver = folder / 'examples_driver.mojo'
    driver.write_text(driver_source(paths))
    binary = folder / 'examples'
    started = time.monotonic()
    build = subprocess.run(
        RUNNER['compiler_command']([str(ROOT / '.pixi/envs/default/bin/mojo'), 'build', '-j1', f'-O{args.optimization}',
                                    '--fp-mode=contract=off', '--Werror', '-I', str(ROOT / 'src'), '-I', str(EXAMPLES),
                                    str(driver), '-o', str(binary)]),
        cwd=ROOT, capture_output=True, text=True, timeout=args.compile_timeout)
    (folder / 'build.log').write_text(build.stdout + build.stderr)
    if build.returncode != 0:
        print((build.stdout + build.stderr)[-6000:])
        print(f'FAILED TO BUILD ({time.monotonic() - started:.0f} s); see {folder / "build.log"}')
        return 1
    print(f'Built {len(paths)} programs in one executable ({time.monotonic() - started:.0f} s)', flush=True)
    results, start, runs = {}, 0, 0
    while start < len(paths):
        run = subprocess.run([str(binary), *(['--from', str(start)] if start else [])], cwd=ROOT,
                             capture_output=True, text=True, timeout=args.run_timeout)
        (folder / f'run{runs}.log').write_text(run.stdout + run.stderr)
        runs += 1
        finished, unfinished, ended = parse(run.stdout)
        results.update(finished)
        if ended:
            break
        crashed = unfinished if unfinished is not None else start
        results[crashed] = (False, '', f'crashed (exit {run.returncode}): {run.stderr.strip()[-2000:]}')
        start = crashed + 1
    failures = []
    for index, path in enumerate(paths):
        passed, output, error = results.get(index, (False, '', 'did not run'))
        expected = declared[path]['stdout']
        if passed and output == expected:
            print(f'PASS {path}')
            continue
        failures.append(path)
        detail = error or ''.join(difflib.unified_diff(expected.splitlines(True), output.splitlines(True),
                                                       'expected', 'actual'))
        print(f'FAIL {path}\n{detail}')
    print(json.dumps(dict(passed=not failures, programs=len(paths), runs=runs, failures=failures,
                          seconds=round(time.monotonic() - started)), indent=2))
    return 1 if failures else 0


if __name__ == '__main__':
    sys.exit(main())
